Algoritmo "trocavalores"

Var
// Seção de Declarações das variáveis 
a,b,c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 a <- 12
 b <- 20
 
 escreval("o valor de A é:",a)
 escreval("o valor de B é:",b)

 c <- a
 a <- b
 b <- c
 
 escreval("**********************")
 escreval("o valor de A é:",a)
 escreval("o valor de B é:",b)
 
Fimalgoritmo